#!/usr/bin/env bash
# Notesy interactive setup — generates .env, creates data dirs, starts the stack.
set -euo pipefail

cd "$(dirname "$0")"

c_red=$'\033[0;31m'; c_grn=$'\033[0;32m'; c_ylw=$'\033[0;33m'; c_bold=$'\033[1m'; c_rst=$'\033[0m'
say()  { printf '%s\n' "$*"; }
info() { printf '%s[*]%s %s\n' "$c_grn" "$c_rst" "$*"; }
warn() { printf '%s[!]%s %s\n' "$c_ylw" "$c_rst" "$*"; }
die()  { printf '%s[x]%s %s\n' "$c_red" "$c_rst" "$*" >&2; exit 1; }

ask() {
    # ask "Prompt" default_value  -> echoes answer
    local prompt="$1" default="${2-}" reply
    if [[ -n "$default" ]]; then
        read -rp "$prompt [$default]: " reply
        printf '%s' "${reply:-$default}"
    else
        read -rp "$prompt: " reply
        printf '%s' "$reply"
    fi
}

ask_password() {
    # ask_password "Prompt"  -> echoes answer (visible; empty -> generate)
    local prompt="$1" reply
    read -rp "$prompt (blank = generate random): " reply
    if [[ -z "$reply" ]]; then
        reply="$(openssl rand -base64 18 | tr -d '/+=' | head -c 20)"
        info "generated random password: $reply"
    fi
    printf '%s' "$reply"
}

yesno() {
    # yesno "Prompt" default(y|n) -> returns 0 for yes
    local prompt="$1" default="${2:-n}" reply
    local hint='[y/N]'; [[ "$default" == y ]] && hint='[Y/n]'
    read -rp "$prompt $hint: " reply
    reply="${reply:-$default}"
    [[ "$reply" =~ ^[Yy] ]]
}


# --- 1. pre-flight ---------------------------------------------------------

info "Checking prerequisites..."

command -v docker >/dev/null 2>&1 \
    || die "docker not found. Install Docker Engine 24+ with the Compose plugin."

docker compose version >/dev/null 2>&1 \
    || die "docker compose plugin not found. Install 'docker-compose-plugin'."

if ! docker info >/dev/null 2>&1; then
    die "Cannot talk to Docker daemon. Is it running, and is this user in the 'docker' group (or run with sudo)?"
fi

command -v openssl >/dev/null 2>&1 || die "openssl not found. Install 'openssl'."

[[ -w . ]] || die "Current directory '$PWD' is not writable by $(whoami); cannot write .env."

info "Docker, Compose, and openssl are present."


# --- 2. mode selection -----------------------------------------------------

say
say "${c_bold}Choose authentication mode:${c_rst}"
say "  1) legacy     — FileBrowser's built-in login (one password per user)"
say "  2) authentik  — SSO via oauth2-proxy + Authentik (requires a configured OIDC provider)"
mode=""
while [[ -z "$mode" ]]; do
    case "$(ask 'Mode' '1')" in
        1|legacy)    mode=legacy ;;
        2|authentik) mode=authentik ;;
        *) warn "Enter 1 or 2." ;;
    esac
done
compose_file="docker-compose.${mode}.yml"
[[ -f "$compose_file" ]] || die "Missing $compose_file in $PWD."
info "Using $compose_file."


# --- 3. collect values -----------------------------------------------------

say
info "Collecting configuration..."

DATA_DIR="$(ask 'Host directory for persistent data' '/opt/notesy')"
FB_USERS="$(ask 'FileBrowser usernames (space-separated)' 'alice bob')"
FB_BRANDING="$(ask 'UI branding name' 'Notes')"

DNS_NAME=""
FB_DEFAULT_USER_PASSWORD=""
OIDC_CLIENT_ID=""
OIDC_CLIENT_SECRET=""
OIDC_ISSUER_URL=""

if [[ "$mode" == legacy ]]; then
    FB_DEFAULT_USER_PASSWORD="$(ask_password 'Initial password for every user')"
else
    DNS_NAME="$(ask 'DNS name users will type in the browser' 'notes.example.local')"
    say
    info "Authentik mode needs values from your OIDC provider."
    OIDC_CLIENT_ID="$(ask 'OIDC client ID')"
    [[ -n "$OIDC_CLIENT_ID" ]] || die "OIDC_CLIENT_ID is required in Authentik mode."
    read -rp "OIDC client secret: " OIDC_CLIENT_SECRET
    [[ -n "$OIDC_CLIENT_SECRET" ]] || die "OIDC_CLIENT_SECRET is required in Authentik mode."
    OIDC_ISSUER_URL="$(ask 'OIDC issuer URL (trailing slash matters)' "https://auth.example.local/application/o/notesy/")"
fi


# --- 4. generate secrets ---------------------------------------------------

info "Generating secrets..."
ONLYOFFICE_JWT_SECRET="$(openssl rand -hex 32)"
CMD_SESSION_SECRET="$(openssl rand -hex 24)"
SESSION_BRIDGE_SECRET=""
OAUTH2_PROXY_COOKIE_SECRET=""
if [[ "$mode" == authentik ]]; then
    SESSION_BRIDGE_SECRET="$(openssl rand -hex 32)"
    OAUTH2_PROXY_COOKIE_SECRET="$(openssl rand -base64 32 | head -c 32)"
fi


# --- 5. write .env ---------------------------------------------------------

if [[ -f .env ]]; then
    yesno ".env already exists. Overwrite?" n || die "Aborted; existing .env left untouched."
    cp .env ".env.bak.$(date +%s)"
    info "Backed up existing .env to .env.bak.$(date +%s)."
fi

umask 077
cat > .env <<EOF
# Generated by setup.sh on $(date -Iseconds)
# Mode: $mode

DATA_DIR=$DATA_DIR
FB_USERS=$FB_USERS
FB_BRANDING=$FB_BRANDING
FB_BRANDING_THEME=dark

ONLYOFFICE_JWT_SECRET=$ONLYOFFICE_JWT_SECRET
CMD_SESSION_SECRET=$CMD_SESSION_SECRET
EOF

if [[ "$mode" == legacy ]]; then
    cat >> .env <<EOF

FB_DEFAULT_USER_PASSWORD=$FB_DEFAULT_USER_PASSWORD
EOF
else
    cat >> .env <<EOF

DNS_NAME=$DNS_NAME
SESSION_BRIDGE_SECRET=$SESSION_BRIDGE_SECRET
OIDC_CLIENT_ID=$OIDC_CLIENT_ID
OIDC_CLIENT_SECRET=$OIDC_CLIENT_SECRET
OIDC_ISSUER_URL=$OIDC_ISSUER_URL
OAUTH2_PROXY_COOKIE_SECRET=$OAUTH2_PROXY_COOKIE_SECRET
EOF
fi
info "Wrote .env (mode=0600)."


# --- 6. data directories ---------------------------------------------------

subdirs=(share database)
[[ "$mode" == authentik ]] && subdirs+=(session-bridge)

need_sudo=0
if [[ ! -d "$DATA_DIR" ]]; then
    parent="$(dirname "$DATA_DIR")"
    [[ -d "$parent" ]] || die "Parent directory '$parent' does not exist."
    [[ -w "$parent" ]] || need_sudo=1
elif [[ ! -w "$DATA_DIR" ]]; then
    need_sudo=1
fi

sudo_cmd=()
if (( need_sudo )); then
    warn "Need elevated privileges to create/chown $DATA_DIR."
    command -v sudo >/dev/null 2>&1 || die "sudo not available and $DATA_DIR is not writable."
    sudo_cmd=(sudo)
fi

for d in "${subdirs[@]}"; do
    target="$DATA_DIR/$d"
    if [[ -d "$target" ]]; then
        info "exists: $target"
    else
        "${sudo_cmd[@]}" mkdir -p "$target"
        info "created: $target"
    fi
done

# Containers run as 1000:1000 (PUID/PGID in the compose env).
"${sudo_cmd[@]}" chown -R 1000:1000 "$DATA_DIR"
info "chown -R 1000:1000 $DATA_DIR"


# --- 7. bring up the stack -------------------------------------------------

say
if yesno "Run 'docker compose -f $compose_file up -d --build' now?" y; then
    info "Building and starting (first build takes 3-5 min on cold cache)..."
    docker compose -f "$compose_file" up -d --build
    say
    browse_url="http://${DNS_NAME:-<this-host>}/"
    info "Stack started. Browse to:  $browse_url"
    say  "Tail logs with:           docker compose -f $compose_file logs -f"
    say  "Stop with:                docker compose -f $compose_file down"
else
    say "Skipped. When ready, run:"
    say "    docker compose -f $compose_file up -d --build"
fi
