#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-911}
PGID=${PGID:-911}

usermod -o -u "$PUID" abc
groupmod -o -g "$PGID" abc

#!/usr/bin/with-contenv bash
PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

lsiown abc:abc /database
lsiown abc:abc /config
lsiown abc:abc /srv